name: Deploy Web Agent Arena to Azure
on:
  push:
    branches: [ main ]
    paths:
      - 'web_agent_arena/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.WEB_AGENT_ARENA_ACR_SERVER }}
        username: ${{ secrets.WEB_AGENT_ARENA_ACR_USERNAME }}
        password: ${{ secrets.WEB_AGENT_ARENA_ACR_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        context: ./web_agent_arena
        push: true
        tags: ${{ secrets.WEB_AGENT_ARENA_ACR_SERVER }}/web-agent-arena:${{ github.sha }}
        file: ./web_agent_arena/Dockerfile

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-agent-arena'
        images: '${{ secrets.WEB_AGENT_ARENA_ACR_SERVER }}/web-agent-arena:${{ github.sha }}'
